#!/usr/bin/env bash
# Installs Nginx
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo service nginx start
